# Generated by Django 4.2.4 on 2023-08-18 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ferramentas',
            name='categoria',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='ferramentas',
            name='curtidas',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ferramentas',
            name='data',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='ferramentas',
            name='data_inclusao',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='ferramentas',
            name='foto_url_1',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='ferramentas',
            name='foto_url_2',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='ferramentas',
            name='nome_ferramenta',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='ferramentas',
            name='origem',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='ferramentas',
            name='origem_url',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='ferramentas',
            name='relacionada_1',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='ferramentas',
            name='relacionada_url_2',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='ferramentas',
            name='site_url',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='ferramentas',
            name='subcategoria',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='ferramentas',
            name='tag_1',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='ferramentas',
            name='tag_2',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='ferramentas',
            name='tag_url_1',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='ferramentas',
            name='tag_url_2',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='ferramentas',
            name='url_youtube_1',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='ferramentas',
            name='url_youtube_2',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
