# Generated by Django 4.2.4 on 2023-08-18 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_ferramentas_categoria_ferramentas_curtidas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ferramentas',
            name='data_inclusao',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
